# LVDS Transeivers - DS91M040
set_property -dict {PACKAGE_PIN L27 IOSTANDARD LVCMOS33} [get_ports STR1_PN_de]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports STR1_PN_di]
set_property -dict {PACKAGE_PIN L26 IOSTANDARD LVCMOS33} [get_ports STR1_PN_re]
set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33} [get_ports STR1_PN_ro]
set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS33} [get_ports STR2_PRD_de]
set_property -dict {PACKAGE_PIN K30 IOSTANDARD LVCMOS33} [get_ports STR2_PRD_di]
set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33} [get_ports STR2_PRD_re]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports STR2_PRD_ro]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33} [get_ports STR3_PRM_de]
set_property -dict {PACKAGE_PIN K28 IOSTANDARD LVCMOS33} [get_ports STR3_PRM_di]
set_property -dict {PACKAGE_PIN K24 IOSTANDARD LVCMOS33} [get_ports STR3_PRM_re]
set_property -dict {PACKAGE_PIN K29 IOSTANDARD LVCMOS33} [get_ports STR3_PRM_ro]
set_property -dict {PACKAGE_PIN J29 IOSTANDARD LVCMOS33} [get_ports STR4_PN_de]
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS33} [get_ports STR4_PN_di]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports STR4_PN_re]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33} [get_ports STR4_PN_ro]