domain_path: D:\Xilinx\Projects\bacon_fw_v9\SW\bacon_v9_platform\export\bacon_v9_platform\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
